/*******************************************************************
Purpose: Class for holding results of the callout 
Parameters: NA
Returns: NA
Throws [Exceptions]: [optional]
********************************************************************/     
public class CallOutResults {
    
    public Integer statusCode;
    public String status;
    public String body;
    public String errorCode;
    public String errorMessage;
    public String errorMoreInfo;
    public String description;
    public String uiDescription;
    public Boolean hasErred;
    public Object response;
}